version: '3.8'

services:
  whoima:
    image: containous/whoami:latest
    command:
      - --port=8081
    deploy:
      placement:
         constraints:
             - node.role != manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.whoima.entrypoints=web
        - traefik.http.routers.whoima.rule=Host(`whoima.slipiconvalley.com`)
        #- traefik.http.routers.whoima.tls=true
        - traefik.http.services.whoima.loadbalancer.server.port=8081
    networks:
      - traefik-public
      
networks:
  traefik-public:
    external: true
